# Generated by Django 4.2.6 on 2023-10-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.CharField(max_length=10)),
                ('allergens', models.ManyToManyField(to='orders.allergen')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('allergens', models.ManyToManyField(to='orders.allergen')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('tip', models.DecimalField(decimal_places=2, max_digits=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.client')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('ingredients', models.ManyToManyField(to='orders.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('cover_charge', models.DecimalField(decimal_places=2, max_digits=30)),
                ('orders', models.ManyToManyField(to='orders.order')),
                ('plates', models.ManyToManyField(to='orders.plate')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.section'),
        ),
        migrations.AddField(
            model_name='order',
            name='plates',
            field=models.ManyToManyField(to='orders.plate'),
        ),
    ]
