# Generated by Django 4.2.6 on 2023-10-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ingredient_allergens_alter_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, to='orders.allergen'),
        ),
    ]
